version: '3'
services:
  order_manager:
    build: .
    container_name: order_manager
    image: order_manager
    ports:
      - 3000:3000
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb/cart
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    command: mongod
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      - AUTH=yes
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
      - MONGODB_INITDB_DATABASE=order-manager
    volumes:
      - ${MONGO_HOST_DATA}/db_order-manager:/data/db


volumes:
  mongodb_server_data: