apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db/
        ports:
        - containerPort: 27017
        env:
          - name: AUTH
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: AUTH
          - name: MONGODB_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: MONGODB_INITDB_ROOT_USERNAME
          - name: MONGODB_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: MONGODB_INITDB_ROOT_PASSWORD
          - name: MONGODB_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: MONGODB_INITDB_DATABASE
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-order-manager
