apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-order-manager
  labels:
    name: pvc-order-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
