apiVersion: v1
kind: Service
metadata:
  name: svc-order-manager
spec:
  type: NodePort
  selector:
    app: order-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
