apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-ms
  template:
    metadata:
      labels:
        app: product-ms
    spec:
      containers:
      - name: product-ms
        image: 975050002971.dkr.ecr.us-east-1.amazonaws.com/product-ms:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /products
            port: 3000
          initialDelaySeconds: 40
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /products
            port: 3000
          initialDelaySeconds: 40
        resources:
          requests:
            cpu: 10m
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: svc-product-ms
spec:
  type: LoadBalancer
  selector:
    app: product-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
